# Generated by Django 3.1.5 on 2022-11-25 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_conversation_conversationmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='inno_email',
            field=models.EmailField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
