# Generated by Django 3.1.5 on 2022-11-29 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='course',
            field=models.CharField(blank=True, choices=[('bs_1', 'Bachelor 1st'), ('bs_2', 'Bachelor 2nd'), ('bs_3', 'Bachelor 3rd'), ('bs_4', 'Bachelor 4th'), ('ms_1', 'Masters 1st'), ('ms_2', 'Masters 2nd'), ('phd', 'Phd')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, choices=[('international', 'International'), ('cis', 'CIS'), ('russian', 'Russian')], max_length=50, null=True),
        ),
    ]
