# Generated by Django 3.1.5 on 2022-12-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='course',
            field=models.CharField(blank=True, choices=[('Bachelor 1st', 'Bachelor 1st'), ('Bachelor 2nd', 'Bachelor 2nd'), ('Bachelor 3rd', 'Bachelor 3rd'), ('Bachelor 4th', 'Bachelor 4th'), ('Master 1st', 'Master 1st'), ('Master 2nd', 'Master 2nd'), ('Phd', 'Phd')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, choices=[('International', 'International'), ('CIS', 'CIS'), ('Russian', 'Russian')], max_length=50, null=True),
        ),
    ]
